app-exemplo/config/routes.rb
Rails.application.routes.draw do
  root to: 'produtos#index'

  resources :produtos
end

app-exemplo/app/models/categoria.rb
class Categoria < ActiveRecord::Base
  include Codificavel

  validates :nome, presence: true, uniqueness: true

  has_many :produtos
end

app-exemplo/app/models/concerns/codificavel.rb
module Codificavel
  extend ActiveSupport::Concern

  included do
    before_validation :definir_codigo
  end

  private
  def definir_codigo
    self.codigo = SecureRandom.hex(6)
  end
end

app-exemplo/app/models/produto.rb
class Produto < ActiveRecord::Base
  include Codificavel

  SITUACOES = %w(ativo inativo esgotado)

  validates_presence_of :nome
  validates_uniqueness_of :nome
  validates_numericality_of :valor, greater_than: 0
  validates_inclusion_of :status, in: SITUACOES

  belongs_to :categoria

  def ativar
    update(status: 'ativo')
  end

  def ativo?
    status == 'ativo'
  end
end

app-exemplo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app-exemplo/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  def create
    @produto = Produto.new(produto_params)

    if @produto.save
      redirect_to @produto, notice: 'Produto was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /produtos/1
  def update
    if @produto.update(produto_params)
      redirect_to @produto, notice: 'Produto was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /produtos/1
  def destroy
    @produto.destroy
    redirect_to produtos_url, notice: 'Produto was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def produto_params
      params.require(:produto).permit(:nome, :valor, :status)
    end
end

app-exemplo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LI2014</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app-exemplo/app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </p>

  <p>
    <%= f.label :valor %>
    <%= f.text_field :valor %>
  </p>

  <p>
    <%= f.label :status %>
    <%= f.select :status, options_from_collection_for_select(Produto::SITUACOES, :to_s, :to_s, @produto.status) %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app-exemplo/app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app-exemplo/app/views/produtos/index.html.erb
<h1>Listing produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Valor</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.valor %></td>
        <td><%= produto.status %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app-exemplo/app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render 'form' %>

<%= link_to 'Back', produtos_path %>

app-exemplo/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Valor</strong>
  <%= @produto.valor %>
</p>

<p>
  <strong>Status</strong>
  <%= @produto.status %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>